spring:
  main:
    allow-circular-references: true
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: postgres
    hikari:
      schema: app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 10000

app:
  cache:
    cacheNames:
      - cacheByCategory
      - cacheByTitleAndAuthor
    caches:
      cacheByCategory:
        expiry: 10m
      cacheByTitleAndAuthor:
        expiry: 10m